[package]
name = "async1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "async1"
path = "src/async1.rs"

[dependencies]
