[package]
name = "async3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "async3"
path = "src/async3.rs"

[dependencies]
anyhow = "1.0.71"
tokio = { version = "1.28.1", features = ["full"] }
