deck_of_cards = "https://deckofcardsapi.com"

[mongo_config]
connection_string = "mongodb://localhost:27017"

[mongo_config.database_info]
database = "testing_showcase"

[mongo_config.database_info.collections]
interactions = "interactions"