[package]
name = "async4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "async4"
path = "src/async4.rs"

[dependencies]
tokio = { version = "1.28.1", features = ["full"] }


